import { useInterviewStore } from './store';

export function generateInterviewReport(): string {
  const state = useInterviewStore.getState();
  const { code, language, integrity, coderabbitReview, latestReview } = state;
  const timestamp = new Date().toLocaleString();

  return `# Daytona Interview Sandbox Report
**Date:** ${timestamp}

## Candidate Solution
**Language:** ${language}

\`\`\`${language}
${code}
\`\`\`

## Integrity Report
${state.getIntegrityReport ? state.getIntegrityReport() : 'N/A'}

- **Tab Blurs:** ${integrity?.blurCount || 0}
- **Paste Events:** ${integrity?.pasteCount || 0}
- **Large Pastes:** ${integrity?.largePasteEvents?.length || 0}

## AI Analysis Summary

### CodeRabbit Review
${coderabbitReview ? coderabbitReview.summary : "No CodeRabbit analysis run."}

### Quick Review (Gemini)
${latestReview ? `Score: ${latestReview.score}/100\nIssues: ${latestReview.issues.length}` : "No quick review run."}

---
*Generated by Daytona Interview Sandbox*
`;
}
